### ISSUE TITLE
valhelsia_structures Logs loot table issues in our server console

### ISSUE THREAD

**Issue by BedrockLegends** [stal111/Valhelsia-Structures#105]
[11.10 02:30:09] [Server] [Worker-Main9/ERROR] [minecraft/LootTableManager]: Couldn't parse loot table valhelsia_structures:blocks/coarse_dirt
[11.10 02:30:09] [Server] java.io.FileNotFoundExceptionvalhelsia_structures:loot_tables/blocks/coarse_dirt.json
[11.10 02:30:09] [Server] 	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:63) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:resources.FallbackResourceManagerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
[11.10 02:30:09] [Server] 	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:61) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:resources.SimpleReloadableResourceManagerAccessor,pl:mixin:APP:kubejs-common.mixins.json:SimpleReloadableResourceManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[11.10 02:30:09] [Server] 	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:39) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A}
[11.10 02:30:09] [Server] 	at dev.latvian.kubejs.core.LootTablesKJS.applyKJS0(LootTablesKJS.java:38) ~[kubejs:1605.3.18-build.{re:mixin,re:classloading}
[11.10 02:30:09] [Server] 	at net.minecraft.loot.LootTableManager.redirect$zon000$applyKJS(LootTableManager.java:521) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A}
[11.10 02:30:09] [Server] 	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A}
[11.10 02:30:09] [Server] 	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A}
[11.10 02:30:09] [Server] 	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
[11.10 02:30:09] [Server] 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
[11.10 02:30:09] [Server] 	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
[11.10 02:30:09] [Server] 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
[11.10 02:30:09] [Server] 	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
[11.10 02:30:09] [Server] 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
[11.10 02:30:09] [Server] 	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) [?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) [?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) [?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
[11.10 02:30:09] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {re:computing_frames}
[11.10 02:30:09] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {re:computing_frames}
[11.10 02:30:09] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}

**Comment by stal111** [comment]
What Valhelsia Structures version are you using?

**Comment by Vaelzan** [comment]
I'm closing this issue as there hasn't been a reply to the question asked. If you still have the problem, you're welcome to reply with the answer and we can look into it again.
