### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ann0nimus** [stal111/Valhelsia-Structures#178]
### Describe the issue

1.19.2 Crash. Game takes 1-2 minutes to load, crashes with error code 0.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.2.0
- Valhelsia Structures: valhelsia_structures-forge-1.19.2-1.0.2.jar
- Valhelsia Core: valhelsia_core-forge-1.19.2-0.5.0.jar
- Valhelsia Furniture: valhelsia_furniture-forge-1.19.2-1.1.1.jar

### Log

```shell
latest.log:
[21:42:08] [main/INFO]: ModLauncher running: args [--username, MinecraftBooiiii, --version, forge-43.2.0, --gameDir, C:\Users\George\curseforge\minecraft\Instances\Level Up RPG, --assetsDir, C:\Users\George\curseforge\minecraft\Install\assets, --assetIndex, 1.19, --uuid, 6420ba8f59e743dda49de8181cc43c03, --accessToken, ????????, --clientId, YzVmZjM0NjEtYmYyOC00NmFlLTkzYjMtMDkzMGFkOThhODM0, --xuid, 2535427661232683, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.0, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[21:42:08] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[21:42:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/George/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
[21:42:08] [main/INFO]: Found mod file valhelsia_core-forge-1.19.2-0.5.0.jar of type MOD with provider {mods folder locator at C:\Users\George\curseforge\minecraft\Instances\Level Up RPG\mods}
[21:42:08] [main/INFO]: Found mod file valhelsia_furniture-forge-1.19.2-1.1.1.jar of type MOD with provider {mods folder locator at C:\Users\George\curseforge\minecraft\Instances\Level Up RPG\mods}
[21:42:08] [main/INFO]: Found mod file valhelsia_structures-forge-1.19.2-1.0.2.jar of type MOD with provider {mods folder locator at C:\Users\George\curseforge\minecraft\Instances\Level Up RPG\mods}
[21:42:08] [main/WARN]: Mod file C:\Users\George\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.0\fmlcore-1.19.2-43.2.0.jar is missing mods.toml file
[21:42:08] [main/WARN]: Mod file C:\Users\George\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.0\javafmllanguage-1.19.2-43.2.0.jar is missing mods.toml file
[21:42:08] [main/WARN]: Mod file C:\Users\George\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.0\lowcodelanguage-1.19.2-43.2.0.jar is missing mods.toml file
[21:42:08] [main/WARN]: Mod file C:\Users\George\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.0\mclanguage-1.19.2-43.2.0.jar is missing mods.toml file
[21:42:08] [main/INFO]: Found mod file fmlcore-1.19.2-43.2.0.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5e76a2bb
[21:42:08] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5e76a2bb
[21:42:08] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5e76a2bb
[21:42:08] [main/INFO]: Found mod file mclanguage-1.19.2-43.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5e76a2bb
[21:42:08] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5e76a2bb
[21:42:08] [main/INFO]: Found mod file forge-1.19.2-43.2.0-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5e76a2bb
[21:42:09] [main/INFO]: No dependencies to load found. Skipping!
[21:42:10] [main/INFO]: Compatibility level set to JAVA_17
[21:42:10] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-43.2.0, --gameDir, C:\Users\George\curseforge\minecraft\Instances\Level Up RPG, --assetsDir, C:\Users\George\curseforge\minecraft\Install\assets, --uuid, 6420ba8f59e743dda49de8181cc43c03, --username, MinecraftBooiiii, --assetIndex, 1.19, --accessToken, ????????, --clientId, YzVmZjM0NjEtYmYyOC00NmFlLTkzYjMtMDkzMGFkOThhODM0, --xuid, 2535427661232683, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[21:42:14] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[21:42:15] [pool-3-thread-1/FATAL]: Mixin apply failed valhelsia_structures.mixins.json:BucketItemMixin -> net.minecraft.world.item.BucketItem: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on valhelsia_placeDousedTorch could not find any targets matching 'emptyContents(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/phys/BlockHitResult;Lnet/minecraft/world/item/ItemStack;)Z' in net.minecraft.world.item.BucketItem. Using refmap valhelsia_structures.refmap.json [PREINJECT Applicator Phase -> valhelsia_structures.mixins.json:BucketItemMixin -> Prepare Injections ->  -> handler$zzj000$valhelsia_placeDousedTorch(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/phys/BlockHitResult;Lnet/minecraft/world/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on valhelsia_placeDousedTorch could not find any targets matching 'emptyContents(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/phys/BlockHitResult;Lnet/minecraft/world/item/ItemStack;)Z' in net.minecraft.world.item.BucketItem. Using refmap valhelsia_structures.refmap.json [PREINJECT Applicator Phase -> valhelsia_structures.mixins.json:BucketItemMixin -> Prepare Injections ->  -> handler$zzj000$valhelsia_placeDousedTorch(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/phys/BlockHitResult;Lnet/minecraft/world/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.item.Item.m_41439_(Item.java:82) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.world.level.block.Block.m_5456_(Block.java:476) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorPresets$Bootstrap.m_226286_(FlatLevelGeneratorPresets.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorPresets$Bootstrap.m_226283_(FlatLevelGeneratorPresets.java:66) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorPresets.m_226274_(FlatLevelGeneratorPresets.java:199) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:665) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at net.minecraft.client.main.Main.lambda$run$0(Main.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Ann0nimus** [comment]
I only have these three mods, the rest are disabled
![image](https://user-images.githubusercontent.com/64259470/236907845-ef3401a7-832e-479a-9539-bd2ab44e7227.png)

**Comment by Vaelzan** [comment]
Update Forge to 43.2.6+, you have an older version of Forge. If for some reason you can't update it, use version 1.0.1 of Valhelsia Structures.

**Comment by Ann0nimus** [comment]
Oh ok thx. I thought that curseforge launcher automatically updates forge version. My bad
