### ISSUE TITLE
[1.15.2] World Loading stuck at 90% after removing the mod

### ISSUE THREAD

**Issue by deadhusk** [stal111/Valhelsia-Structures#7]
Minecraft **1.15.2**
Forge **31.1.47**
Valhelsia **15.0.2a**

 _No other mods than VS are used on generation
No mods are used when attempting to enter the world_

I've generated a world with VS present, flew to a random structure and left the game. Then I removed VS and tried entering the same world. It gets stuck on 87% or 90% loading. The game doesn't crash compleltely but freezes without the possibility to do anything. 

I've tried removing the spawner block and the code surrounding it previously with the same result so that doesn't seem to be the case. 

<details>
  <summary>Log</summary>
  
  ```[m[32m[02:59:21] [Render thread/INFO] [minecraft/Minecraft]: Setting user: mynickname
[m[32m[03:00:06] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.2.2 build 10
[m[32m[03:00:16] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 31.1.47, for MC 1.15.2 with MCP 20200414.225201
[m[32m[03:00:16] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v31.1.47 Initialized
[m[32m[03:00:28] [Render thread/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[m[32m[03:00:28] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, Mod Resources
[m[32m[03:01:29] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[m[32m[03:01:32] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: OUTDATED Current: 31.1.47 Target: 31.1.48
[m[32m[03:01:40] [Render thread/INFO] [minecraft/SoundSystem]: OpenAL initialized.
[m[32m[03:01:40] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
[m[32m[03:01:41] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 1024x512x0 minecraft:textures/atlas/blocks.png-atlas
[m[32m[03:01:41] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 128x128x0 minecraft:textures/atlas/signs.png-atlas
[m[32m[03:01:41] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[m[32m[03:01:41] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[m[32m[03:01:41] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[m[32m[03:01:41] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[m[32m[03:01:41] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[m[32m[03:01:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[m[32m[03:01:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[m[32m[03:01:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[m[33m[03:01:49] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[m[33m[03:01:49] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[33m[03:01:49] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[33m[03:01:49] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[m[33m[03:01:49] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[32m[03:01:49] [Server thread/INFO] [minecraft/IntegratedServer]: Starting integrated minecraft server version 1.15.2
[m[32m[03:01:49] [Server thread/INFO] [minecraft/IntegratedServer]: Generating keypair
[m[1;31m[03:01:50] [Server thread/ERROR] [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod valhelsia_structures which appears to be missing, things may not work well
[m[1;31m[03:01:50] [Server thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:block
	valhelsia_structures:special_spawner: 680

[m[1;31m[03:01:50] [Server thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:item
	valhelsia_structures:special_spawner: 884

[m[1;31m[03:01:55] [Server thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: There are unidentified mappings in this world - we are going to attempt to process anyway
[m[33m[03:01:55] [Server thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:valhelsia_structures
[m[32m[03:01:55] [Server thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.15.2-31.1.47-universal.jar
[m[32m[03:01:56] [Server thread/INFO] [minecraft/RecipeManager]: Loaded 6 recipes
[m[32m[03:01:58] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 825 advancements
[m[32m[03:01:59] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
[m[1;31m[03:02:01] [Server thread/ERROR] [minecraft/Structures]: Unknown feature id: valhelsia_structures:small_dungeon
[m[32m[03:02:02] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:02] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:02] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:02] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:02] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:02] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:02] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:03] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[03:02:03] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 68%
[m[33m[03:02:03] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id valhelsia_structures:special_spawner
[m[33m[03:02:03] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id valhelsia_structures:special_spawner
[m[33m[03:02:03] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id valhelsia_structures:special_spawner
[m[33m[03:02:03] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id valhelsia_structures:special_spawner
[m[33m[03:02:03] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id valhelsia_structures:special_spawner
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:11] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:12] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:12] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:13] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:13] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:14] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:14] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:15] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:15] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:16] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m[32m[03:02:16] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 85%
[m[32m[03:02:17] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 86%
[m[33m[03:02:17] [Server-Worker-7/WARN] [minecraft/Util]: Server-Worker-7 died
java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251] {}
Caused by: net.minecraft.crash.ReportedException: Exception generating new chunk
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:530) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517) ~[?:?] {re:classloading}
	... 12 more
Caused by: java.lang.NullPointerException
	at net.minecraft.world.gen.ChunkGenerator.func_222528_a(ChunkGenerator.java:186) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$3(ChunkStatus.java:52) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:519) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517) ~[?:?] {re:classloading}
	... 12 more
[m[32m[03:02:17] [Server-Worker-7/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/25/20 3:02 AM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkGenerator.func_222528_a(ChunkGenerator.java:186) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$3(ChunkStatus.java:52) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:519) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_251] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server-Worker-7
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_222528_a(ChunkGenerator.java:186)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$3(ChunkStatus.java:52)
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195)

-- Chunk to be generated --
Details:
	Location: 8,17
	Position hash: 73014444040
	Generator: net.minecraft.world.gen.OverworldChunkGenerator@6ff3f1e6
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:519)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1246184240 bytes (1188 MB) / 1693974528 bytes (1615 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1524m -Xmx2048m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.47-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.47-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.47-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.47-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.47-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.47
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.47-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.1.47-universal.jar Forge {forge@31.1.47 DONE}
[m[32m[03:02:17] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 88%
  ```
  
</details>

**Comment by Vaelzan** [comment]
If this is happening after the mod is removed, then I have to assume that the bug lies in either Minecraft or Forge (well, probably Minecraft, but Forge can patch Minecraft to fix vanilla bugs). It's almost certainly a bug that was triggered by Valhelsia Structures being there and then removed, but the bug itself isn't in the mod.

Specifically, the vanilla code appears to be missing a null check. I haven't looked at the code yet though, just the stack trace. It may be possible that we can investigate further and then forward something to the Forge team once we know more.
